# API Credentials
#vikash
GOOGLE_API_KEY = "AIzaSyBW8Q293kkAvwtluqCn9dYcwZf0H5lTboE"
#harsha
#GOOGLE_API_KEY = "AIzaSyC5kjICaMi_P_Qfm22ruD_1jwmxy3Xk4vw"
#narendra
#GOOGLE_API_KEY ="AIzaSyC0hS-DqhxbeQae9vdZvkaMGYiqkP9GkuA"
#afrin
#GOOGLE_API_KEY ="AIzaSyADCV3-8tSG5809J9niwlRc32QWbJTA9JQ"
#saniya
#GOOGLE_API_KEY ="AIzaSyDWskWS9lTNw1YXyLC6C2IDXTLOMee0thA"